Repository Azure/azure-storage-fuse, pull requests merged in 2022-09, with the labels that each got.

#880 Expand path
  azure-pipeline-templates/mount-test.yml
  cmd/health-monitor.go
  cmd/mount.go
  cmd/mountgen1.go
  cmd/mountgen1_test.go
  cmd/mountv1.go
  common/util.go
  common/util_test.go
  component/file_cache/file_cache.go
  test/mount_test/mount_test.go
Labels: bug, V2

#887 Make writeback cache default
  CHANGELOG.md
  README.md
  azure-pipeline-templates/distro-tests.yml
  component/libfuse/libfuse.go
  component/libfuse/libfuse2_handler_test_wrapper.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_handler_test.go
  component/libfuse/libfuse_handler_test_wrapper.go
  setup/baseConfig.yaml
  test/e2e_tests/dir_test.go
  testdata/config/azure_key.yaml
  testdata/config/azure_key_emptyfile.yaml
  testdata/config/azure_key_hmon.yaml
  testdata/config/azure_key_huge.yaml
  testdata/config/azure_key_lfu.yaml
  testdata/config/azure_key_lru_purge.yaml
  testdata/config/azure_key_proxy.yaml
  testdata/config/azure_msi.yaml
  testdata/config/azure_sas.yaml
  testdata/config/azure_sas_proxy.yaml
  testdata/config/azure_spn.yaml
  testdata/config/azure_spn_proxy.yaml
  testdata/config/azure_stream.yaml
  testdata/config/config_key.yaml
  testdata/config/config_msi.yaml
  testdata/config/config_sas.yaml
  testdata/config/config_spn.yaml
Labels: bug, V2

#891 Update version
  blobfuse2-release.yaml
  common/types.go
Labels: V2

#893 Clean up exit 1 errors for blobfuse2
  blobfuse2-code-coverage.yaml
  blobfuse2-nightly.yaml
  cmd/config-gen.go
  cmd/doc.go
  cmd/generator.go
  cmd/health-monitor.go
  cmd/mount.go
  cmd/mount_all.go
  cmd/mount_list.go
  cmd/mountgen1.go
  cmd/mountv1.go
  cmd/root.go
  cmd/root_test.go
  cmd/secure.go
  cmd/secure_get.go
  cmd/secure_set.go
  cmd/unmount.go
  cmd/unmount_all.go
  cmd/version.go
  common/config/config_parser.go
  common/log/logger.go
  common/types.go
  common/util.go
  component/azstorage/azauthmsi.go
  component/azstorage/azauthspn.go
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/azstorage/utils.go
  component/file_cache/file_cache.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
  setup/baseConfig.yaml
  test/mount_test/mount_test.go
  testdata/config/azure_key_hmon.yaml
  tools/health-monitor/main.go
  tools/health-monitor/monitor/blobfuse_stats/stats_reader.go
Labels: V2

#896 Auto detect auth mode if user has not provided it as config
  component/azstorage/config.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
Labels: V2

#899 Readme for health monitor
  cmd/health-monitor.go
  setup/baseConfig.yaml
  tools/health-monitor/README.md
  tools/health-monitor/common/types.go
  tools/health-monitor/main.go
Labels: V2

#897 Unit tests for mount, mountv1 and doc commands
  blobfuse2-code-coverage.yaml
  cmd/doc_test.go
  cmd/mount.go
  cmd/mount_test.go
  cmd/mountv1_test.go
Labels: V2

#876 filesfuse e2e testing
  azure-pipeline-templates/e2e-tests.yml
  azure-pipeline-templates/release-distro-tests.yml
  component/azstorage/file_share.go
  test/e2e_tests/data_validation_test.go
  test/e2e_tests/dir_test.go
  test/e2e_tests/file_test.go
Labels: V2, FileFuse

#898 Fixed parsing of endpoint to support blob endpoints for ADLS accounts
  CHANGELOG.md
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/datalake_test.go
  component/azstorage/utils_test.go
Labels: V2

#902 Adding component governance to ci pipeline
  blobfuse2-ci.yaml
Labels: V2

#904 Correct Migration guide installation instructions
  MIGRATION.md
Labels: V2

#907 Health Monitor Readme + Generated CLI Docs
  README.md
  TSG.md
  doc/blobfuse2.md
  doc/blobfuse2_completion.md
  doc/blobfuse2_completion_bash.md
  doc/blobfuse2_completion_fish.md
  doc/blobfuse2_completion_powershell.md
  doc/blobfuse2_completion_zsh.md
  doc/blobfuse2_mount.md
  doc/blobfuse2_mount_all.md
  doc/blobfuse2_mount_list.md
  doc/blobfuse2_mountv1.md
  doc/blobfuse2_secure.md
  doc/blobfuse2_secure_decrypt.md
  doc/blobfuse2_secure_encrypt.md
  doc/blobfuse2_secure_get.md
  doc/blobfuse2_secure_set.md
  doc/blobfuse2_unmount.md
  doc/blobfuse2_unmount_all.md
  doc/blobfuse2_version.md
Labels: V2

#888 Run scripts in performance pipeline
  blobfuse2-perf.yaml
  test/scripts/cppparrun.sh
  test/scripts/fio.sh
  test/scripts/git_clone.sh
  test/scripts/goparrun.sh
  test/scripts/run.sh
  testdata/config/azure_key_perf.yaml
Labels: V2

#909 Adding UT for mount all and gen1fuse CLIs
  blobfuse2-code-coverage.yaml
  cmd/mountgen1.go
  cmd/mountgen1_test.go
Labels: V2

#922 Reset per file coverage threshold to 70%
  test/scripts/coveragecheck.sh
Labels: V2
