Repository Azure/azure-storage-fuse, pull requests merged in 2022-04, with the labels that each got.

#754 Fixed bug where remount on empty containers was not throwing error when the mount path has trailing '/'
  common/util.go
Labels: bug, V2

#755 Fixed issue where DIRECT flag was not masked out in libfuse3 component
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse2_handler_test_wrapper.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_handler_test.go
  component/libfuse/libfuse_handler_test_wrapper.go
Labels: bug, V2

#756 Support . and .. in ls
  component/libfuse/libfuse.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
Labels: V2

#759 [BUG] Fixed block size max blocks exceeded bug when blocksize not set
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/datalake_test.go
Labels: bug, V2

#762 Set flag parsing to exit on error to ensure exit status is non zero
  azure-pipeline-templates/invalid-command-tests.yml
  blobfuse2-nightly.yaml
  cmd/config-gen.go
  cmd/generator.go
  cmd/mount.go
  cmd/mount_all.go
  cmd/mount_list.go
  cmd/mountgen1.go
  cmd/mountv1.go
  cmd/root.go
  cmd/secure.go
  cmd/secure_get.go
  cmd/secure_set.go
  cmd/unmount.go
  cmd/unmount_all.go
  cmd/version.go
  go.mod
  go.sum
Labels: bug, V2

#757 Test cases for mount command
  azure-pipeline-templates/mount-test.yml
  azure-pipeline-templates/verbose-tests.yml
  component/azstorage/block_blob.go
  test/mount_test/mount_test.go
Labels: V2

#765 Temporarily fixed fio error caused due to race condition between OpenFile and CloseFile
  component/file_cache/lfu_policy.go
  component/file_cache/lru_policy.go
Labels: bug, V2

#768 Correction with Block Size calculation for upload
  common/log/base_logger.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
Labels: bug, V2

#767 Fixing large download in single request issue
  cpplite/src/blob/blob_client_wrapper.cpp
Labels: bug, V1

#769 Deprecate using 3rd party eviction policies
  .github/workflows/codespell.yml
  cmd/mountv1.go
  cmd/mountv1_test.go
  common/cache_policy/lru_policy.go
  component/stream/stream.go
  component/stream/stream_cache.go
  component/stream/stream_test.go
  internal/handlemap/handle_map.go
  setup/baseConfig.yaml
Labels: V2
