Repository Azure/azure-storage-fuse, pull requests merged in 2022-10, with the labels that each got.

#914 Docker installation and container image build
  README.md
  component/libfuse/libfuse2_handler_test_wrapper.go
  docker/Dockerfile
  docker/buildandruncontainer.sh
  docker/config.yaml
  docker/dockerinstall.sh
  docker/publishcontainer.sh
  test/scripts/depends.sh
Labels: V2

#925 Fix release pipeline
  azure-pipeline-templates/release-distro-tests.yml
Labels: V2

#924 Mount using /etc/fstab
  CHANGELOG.md
  blobfuse2-code-coverage.yaml
  blobfuse2-gen1-artifacts.yaml
  blobfuse2-release.yaml
  cmd/mount.go
  cmd/mount_test.go
  cmd/mountv1.go
  cmd/mountv1_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/unmount.go
  cmd/unmount_all.go
  cmd/unmount_test.go
  common/types.go
  component/azstorage/config_test.go
  component/azstorage/connection.go
  internal/handlemap/handle_map.go
  internal/handlemap/handle_map_test.go
Labels: bug, V2

#927 Added support to work with virtual directories without the special marker directory blob
  CHANGELOG.md
  README.md
  cmd/mountv1.go
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/connection.go
  component/azstorage/utils.go
  setup/baseConfig.yaml
Labels: enhancement, V2

#933 Change https_proxy / http_proxy example to a working example
  README.md
Labels: documentation, V2

#929 Vibhansa/v2/newvmaddition
  blobfuse2-nightly.yaml
  blobfuse2-release.yaml
  setup/blobfuse2.service
  test/scripts/fio.sh
  test/scripts/git_clone.sh
  test/scripts/run.sh
Labels: enhancement, V2

#926 MSI Object ID Credential Support
  azure-pipeline-templates/build-release.yml
  azure-pipeline-templates/build.yml
  blobfuse2-ci.yaml
  component/azstorage/azauth.go
  component/azstorage/azauth_test.go
  component/azstorage/azauthmsi.go
  component/azstorage/config.go
  component/azstorage/config_test.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
Labels: enhancement, V2

#943 FIO Test additions
  blobfuse2-perf.yaml
  component/azstorage/azauth_test.go
  component/azstorage/block_blob.go
  component/file_cache/lru_policy.go
  test/scripts/fio.sh
Labels: V2

#947 Retry listing if server returned back empty list but a new marker was given
  CHANGELOG.md
  TSG.md
  component/azstorage/azstorage.go
  component/azstorage/datalake.go
  component/azstorage/utils.go
  setup/baseConfig.yaml
Labels: bug, V2

#952 Health monitor CLI tests
  blobfuse2-code-coverage.yaml
  cmd/health-monitor.go
  cmd/health-monitor_test.go
Labels: V2

#955 Added stream data validation test cases
  azure-pipeline-templates/distro-tests.yml
  azure-pipeline-templates/e2e-tests.yml
  blobfuse2-nightly.yaml
  test/e2e_tests/data_validation_test.go
  test/e2e_tests/dir_test.go
  test/e2e_tests/file_test.go
  testdata/config/azure_stream_direct.yaml
  testdata/config/azure_stream_filename_direct.yaml
Labels: V2
