Repository Azure/azure-storage-fuse, pull requests merged in 2022-07, with the labels that each got.

#830 Update readme to point to v2
  README.md
Labels: V1

#829 Vibhansa/v2/resource msi change
  CHANGELOG.md
  cmd/mountv1.go
  component/azstorage/azauth.go
  component/azstorage/azauthmsi.go
  component/azstorage/config.go
  component/azstorage/datalake.go
  go.mod
  go.sum
  setup/baseConfig.yaml
Labels: bug, V2

#833 Files mvp interface methods
  component/azstorage/file_share.go
  component/azstorage/utils.go
Labels: V2

#832 Code coverage threshold check
  blobfuse2-code-coverage.yaml
  test/scripts/coveragecheck.sh
Labels: V2

#835 Block mounted directory list calls
  NOTICE
  component/azstorage/azstorage.go
Labels: bug, V2

#837 Dont delete directory in case of gen2 account if directory is not empty
  CMakeLists.txt
  blobfuse/directoryapis.cpp
  blobfuse/src/DataLakeBfsClient.cpp
  cpplite/include/constants.dat
Labels: bug, V1

#838 V2 : Dont delete directory based on local cache status
  CHANGELOG.md
  component/file_cache/file_cache.go
Labels: bug, V2

#842 Blobfuse2 Starter TSG
  TSG.md
Labels: V2

#840 File and dir setup methods
  component/azstorage/file_share.go
  component/azstorage/file_share_test.go
Labels: V2, FileFuse

#841 Migrated release pipeline to 1es
  blobfuse-artifacts.yml
Labels: V1

#839 Migrated nightly pipeline to 1es
  blobfuse-nightly.yml
Labels: V1

#845 Background auth validation fix
  CHANGELOG.md
  cmd/mount.go
  cmd/mount_all.go
  component/attr_cache/attr_cache.go
  component/attr_cache/attr_cache_test.go
  component/azstorage/azstorage.go
  component/azstorage/block_blob_test.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
  component/libfuse/libfuse.go
  component/libfuse/libfuse2_handler_test_wrapper.go
  component/libfuse/libfuse_handler_test_wrapper.go
  component/loopback/loopback_fs.go
  component/stream/read_test.go
  component/stream/stream.go
  internal/base_component.go
  internal/component.go
  internal/mock_component.go
  internal/pipeline.go
Labels: bug, V2
