Repository Azure/azure-storage-fuse, pull requests merged in 2022-08, with the labels that each got.

#852 Point customers to v2 in Github issue template
  .github/ISSUE_TEMPLATE.md
Labels: V2

#849 Code coverage addition for generate config cli
  azure-pipeline-templates/distro-tests.yml
  azure-pipeline-templates/e2e-tests.yml
  blobfuse2-ci.yaml
  blobfuse2-code-coverage.yaml
  blobfuse2-nightly.yaml
  blobfuse2-perf.yaml
  blobfuse2-release.yaml
  build.sh
  internal/pipeline_test.go
  test/e2e_tests/data_validation_test.go
  test/e2e_tests/dir_test.go
  test/e2e_tests/file_test.go
Labels: V2

#850 Nightly pipeline fix
  CMakeLists.txt
  blobfuse-artifacts.yml
  blobfuse-nightly.yml
  blobfuse/include/AttrCacheBfsClient.h
  blobfuse/src/AttrCacheBfsClient.cpp
  blobfuse/src/BlockBlobBfsClient.cpp
  blobfuse/src/DataLakeBfsClient.cpp
  cpplite/include/constants.dat
  test/feature_test.go
Labels: V1

#848 Adding extra auth validation cases
  azure-pipeline-templates/build.yml
  blobfuse2-ci.yaml
  blobfuse2-code-coverage.yaml
  component/azstorage/azauth_test.go
Labels: V2

#856 Stablizing pipelines and adding more test cases
  azure-pipeline-templates/release-distro-tests.yml
  azure-pipeline-templates/verbose-tests.yml
  blobfuse2-release.yaml
  test/e2e_tests/dir_test.go
Labels: V2

#851 Added a debug option to debug libcurl
  README.md
  blobfuse/blobfuse.cpp
  blobfuse/include/BlobfuseGlobals.h
  blobfuse/include/DfsProperties.h
  blobfuse/include/OAuthTokenCredentialManager.h
  blobfuse/src/BlobfuseGlobals.cpp
  cpplite/include/blob/blob_client.h
  cpplite/include/http/libcurl_http_client.h
  cpplite/src/http/libcurl_http_client.cpp
Labels: V1

#855 Miscellaneous Tests
  blobfuse2-code-coverage.yaml
  cmd/secure_test.go
  common/config/keys_tree_test.go
  common/types.go
  common/util_test.go
  component/libfuse/libfuse_handler_test.go
Labels: V2

#857 Added MSI Tests and more to code coverage
  .gitignore
  CHANGELOG.md
  blobfuse2-code-coverage.yaml
  component/azstorage/azauth_test.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
Labels: V2

#858 Retry on timeout error from server
  CHANGELOG.md
  azure-pipeline-templates/distro-tests.yml
  azure-pipeline-templates/e2e-tests.yml
  azure-pipeline-templates/release-distro-tests.yml
  azure-pipeline-templates/verbose-tests.yml
  blobfuse2-ci.yaml
  blobfuse2-code-coverage.yaml
  blobfuse2-nightly.yaml
  blobfuse2-release.yaml
  component/azstorage/block_blob.go
  component/azstorage/datalake.go
  component/azstorage/utils.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
  component/stream/read_test.go
  go.sum
  test/e2e_tests/data_validation_test.go
  test/e2e_tests/dir_test.go
Labels: V2

#865 Added Azurite Test
  azure-pipeline-templates/distro-tests.yml
  azure-pipeline-templates/e2e-tests.yml
  azure-pipeline-templates/release-distro-tests.yml
  azure-pipeline-templates/verbose-tests.yml
  blobfuse2-code-coverage.yaml
  blobfuse2-nightly.yaml
  blobfuse2-perf.yaml
  test/e2e_tests/data_validation_test.go
  test/e2e_tests/dir_test.go
  test/e2e_tests/file_test.go
  testdata/config/azure_key.yaml
Labels: V2

#867 Upgrade version to preview 3
  common/types.go
Labels: V2

#859 File read write methods + some unit testing
  component/azstorage/file_share.go
  component/azstorage/file_share_test.go
  component/file_cache/file_cache.go
  go.mod
  go.sum
Labels: V2, FileFuse

#861 Streaming small fixes + more tests
  azure-pipeline-templates/verbose-tests.yml
  blobfuse2-nightly.yaml
  component/attr_cache/attr_cache.go
  component/stream/connection.go
  component/stream/read.go
  component/stream/read_test.go
  component/stream/read_write.go
  component/stream/read_write_test.go
  component/stream/stream.go
  test/e2e_tests/dir_test.go
  testdata/config/azure_stream.yaml
Labels: V2

#874 Add missing file-cache cli (compared with v1)
  MIGRATION.md
  component/file_cache/file_cache.go
Labels: V2

#863 MD5 Sum updation on upload and validation on download
  CHANGELOG.md
  blobfuse2-code-coverage.yaml
  blobfuse2-release.yaml
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/connection.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
  component/file_cache/file_cache.go
  internal/attribute.go
  setup/baseConfig.yaml
  test/accoutcleanup/accountcleanup_test.go
Labels: V2

#875 Changes for enabling writeback cache
  CHANGELOG.md
  component/libfuse/libfuse.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_handler_test.go
  setup/baseConfig.yaml
Labels: V2

#872 Added scripts to generate output conveniently
  test/scripts/cppparrun.sh
  test/scripts/fio.sh
  test/scripts/git_clone.sh
  test/scripts/goparrun.sh
  test/scripts/pread.sh
  test/scripts/pwrite.sh
  test/scripts/run.sh
Labels: V2

#877 Add missing cli options to readme
  README.md
  component/azstorage/azstorage.go
Labels: V2

#868 Health monitor
  .gitignore
  NOTICE
  azure-pipeline-templates/build-release.yml
  azure-pipeline-templates/build.yml
  blobfuse2-ci.yaml
  blobfuse2-nightly.yaml
  blobfuse2-release.yaml
  build.sh
  cmd/health-monitor.go
  cmd/mount.go
  common/log/base_logger.go
  common/log/logger.go
  common/log/sys_logger.go
  common/types.go
  common/util.go
  component/azstorage/azstorage.go
  component/azstorage/azstorage_constants.go
  component/azstorage/block_blob.go
  component/file_cache/cache_policy.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_constants.go
  component/libfuse/libfuse.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_constants.go
  component/libfuse/libfuse_handler.go
  copyright_fix.sh
  go.mod
  go.sum
  internal/stats_manager/stats_common.go
  internal/stats_manager/stats_manager.go
  setup/12-bfusemon.conf
  setup/baseConfig.yaml
  setup/blobfuse2-logrotate
  testdata/config/azure_key_hmon.yaml
  tools/health-monitor/common/types.go
  tools/health-monitor/common/util.go
  tools/health-monitor/internal/factory.go
  tools/health-monitor/internal/monitor.go
  tools/health-monitor/internal/stats_export.go
  tools/health-monitor/main.go
  tools/health-monitor/monitor/blobfuse_stats/stats_reader.go
  tools/health-monitor/monitor/cpu_profiler/cpu_monitor.go
  tools/health-monitor/monitor/file_cache/cache_monitor.go
  tools/health-monitor/monitor/file_cache/types_cache.go
  tools/health-monitor/monitor/imports.go
  tools/health-monitor/monitor/memory_profiler/memory_monitor.go
  tools/health-monitor/monitor/network_profiler/network_monitor.go
Labels: V2

#884 remove assignment and add comparison to storage_errno
  blobfuse/fileapis.cpp
Labels: V1

#883 Vibhansa/v2/healthmon coverage supress
  blobfuse2-code-coverage.yaml
Labels: V2

#881 Added supported v1 CLI parameters to v2
  MIGRATION.md
  README.md
  cmd/mount.go
  cmd/mountv1.go
  cmd/mountv1_test.go
  common/config/config_parser.go
  common/config/keys_tree.go
  common/types.go
  component/attr_cache/attr_cache.go
  component/azstorage/azstorage.go
  component/azstorage/config.go
  component/file_cache/file_cache.go
  component/libfuse/libfuse.go
  component/stream/read.go
  component/stream/read_write.go
  component/stream/stream.go
Labels: V2
