Repository Azure/azure-storage-fuse, pull requests merged in 2022-11, with the labels that each got.

#956 Added a streaming guide
  STREAMING.md
Labels: V2

#944 URL update for security warnings + MSI based deb-9 tests
  blobfuse2-nightly.yaml
  blobfuse2-release.yaml
  common/version.go
  docker/buildandruncontainer.sh
  docker/buildcontainer.sh
  testdata/config/azure_msi_sysid.yaml
Labels: V2

#959 correct esrp code signing connection name for v2
  blobfuse2-release.yaml
Labels: V2

#960 Correct version and update Changelog post preview.4 release
  CHANGELOG.md
  common/stats_collector/stats.go
  common/stats_collector/stats_collector.go
  common/stats_monitor/stats_monitor.go
  common/types.go
  test/statscollectortest.go
Labels: V2

#961 Added proxy test to code coverage pipeline
  blobfuse2-code-coverage.yaml
Labels: V2

#962 Fixed release pipeline UT
  azure-pipeline-templates/build-release.yml
  blobfuse2-release.yaml
Labels: V2

#963 Created stages for data validation pipeline to improve runnability
  azure-pipeline-templates/distro-tests.yml
  azure-pipeline-templates/e2e-tests-spcl.yml
  azure-pipeline-templates/e2e-tests.yml
  azure-pipeline-templates/setup.yml
  blobfuse2-nightly.yaml
Labels: V2

#967 [fixed] unexpected maximum might incur security issues.
  blobfuse/src/BlobStreamer.cpp
Labels: V1

#971 Fixed a bug where some directories would be listed twice
  CHANGELOG.md
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
Labels: bug, V2

#965 Add retry in rename call when deletion fails and correct retry policy
  CHANGELOG.md
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/datalake_test.go
  setup/baseConfig.yaml
Labels: V2

#974 Cleanup of nightly pipeline to increase parallelism
  azure-pipeline-templates/distro-tests.yml
  azure-pipeline-templates/verbose-tests.yml
  blobfuse2-nightly.yaml
Labels: V2

#973 Fix mountall command
  CHANGELOG.md
  cmd/mount_all.go
Labels: bug, V2

#975 Subdirectory as cli option and support for nonempty libfuse option
  CHANGELOG.md
  README.md
  cmd/mount.go
  cmd/mount_test.go
  cmd/mountv1.go
  cmd/mountv1_test.go
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/datalake_test.go
  component/libfuse/libfuse.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_defs.h
  component/libfuse/libfuse_handler.go
  setup/baseConfig.yaml
Labels: V2

#982 Fix for GLIBC error in release pipelines
  blobfuse2-release.yaml
Labels: V2

#985 Release pipeline failure resolution
  CHANGELOG.md
  azure-pipeline-templates/release-distro-tests.yml
  blobfuse2-release.yaml
  common/types.go
Labels: V2
