Repository Azure/azure-storage-fuse, pull requests merged in 2023-06, with the labels that each got.

#1163 Remove leading slashes from subdirectory name
  CHANGELOG.md
  component/azstorage/config.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
Labels: V2

#1162 Adding FUSE option direct_io
  CHANGELOG.md
  azure-pipeline-templates/verbose-tests.yml
  cmd/mount.go
  cmd/mount_test.go
  component/libfuse/libfuse.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_handler_test.go
  setup/baseConfig.yaml
  test/e2e_tests/file_test.go
  testdata/config/azure_key_directio.yaml
Labels: V2

#1169 Fix resource string in SPN token generation
  CHANGELOG.md
  README.md
  blobfuse2-code-coverage.yaml
  component/azstorage/azauthspn.go
  component/azstorage/config.go
Labels: V2

#1176 Vibhansa/v2/bug 1175
  CHANGELOG.md
  component/stream/stream.go
Labels: bug

#1174 Auth permission mismatch error check from azstorage
  CHANGELOG.md
  component/azstorage/block_blob.go
  component/azstorage/datalake.go
  component/azstorage/utils.go
  component/file_cache/file_cache.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
Labels: bug

#1183 Update cli docs for mount command
  doc/blobfuse2_mount.md
  doc/blobfuse2_mount_all.md
  doc/blobfuse2_mount_list.md
Labels: documentation, V2

#1180 Fix function names in logs and log more
  component/attr_cache/attr_cache.go
  component/azstorage/config.go
  component/file_cache/file_cache.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
  component/loopback/loopback_fs.go
  component/stream/read.go
  component/stream/read_write.go
  component/stream/read_write_filename.go
  tools/health-monitor/internal/stats_export.go
  tools/health-monitor/monitor/blobfuse_stats/stats_reader.go
Labels: V2

#1184 Updating dependencies
  NOTICE
  go.mod
  go.sum
Labels: V2

#1188 Create temp cach path recursively if it does not exists
  .github/CODEOWNERS
  CHANGELOG.md
  component/file_cache/file_cache.go
Labels: bug, V2

#1189 Resolve high cpu usage even on idle system
  CHANGELOG.md
  component/azstorage/block_blob.go
Labels: bug
