Repository Azure/azure-storage-fuse, pull requests merged in 2023-08, with the labels that each got.

#1213 Multiple bug fixes
  CHANGELOG.md
  azure-pipeline-templates/e2e-tests.yml
  blobfuse2-nightly.yaml
  cmd/health-monitor_stop_all.go
  cmd/unmount.go
  cmd/unmount_test.go
  component/azstorage/azauth_test.go
  component/file_cache/cache_policy.go
  component/file_cache/cache_policy_test.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
  component/file_cache/lru_policy.go
  component/libfuse/libfuse.go
Labels: V2

#1214 Telemetry header addition
  CHANGELOG.md
  component/azstorage/azstorage.go
  component/azstorage/config.go
  component/azstorage/connection.go
  component/azstorage/utils.go
  component/libfuse/libfuse.go
  setup/baseConfig.yaml
  test/longhaul/longhaul.sh
  test/longhaul/stresstest.sh
  test/longhaul/telemetrytest.sh
Labels: V2, feature request

#1216 Rename leaving destination file in temp-cache for ever
  CHANGELOG.md
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
Labels: bug, V2

#1217 RHEL 9 and Mariner 2 nightly test
  blobfuse2-nightly.yaml
  blobfuse2-release.yaml
Labels: V2

#1224 lseek() on dir handle does not work as expected
  README.md
  test/test_utils/dir_list_seek.c
Labels: documentation, V2

#1219 Adding support for ARM64
  CHANGELOG.md
  azure-pipeline-templates/blobfuse2-ci-template.yml
  azure-pipeline-templates/build-release.yml
  azure-pipeline-templates/build.yml
  azure-pipeline-templates/setup.yml
  blobfuse2-ci.yaml
  blobfuse2-code-coverage.yaml
  blobfuse2-nightly.yaml
  blobfuse2-release.yaml
  cmd/health-monitor_test.go
  go_installer.sh
Labels: V2, feature request

#1229 Updated README
  CHANGELOG.md
  README.md
Labels: documentation, V2

#1231 Fix related to direct_io
  cmd/mount.go
  component/libfuse/libfuse.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
Labels: V2, direct_io

#1181 Adaptive Prefetch Streaming
  CHANGELOG.md
  NOTICE
  README.md
  azure-pipeline-templates/e2e-tests-block-cache.yml
  azure-pipeline-templates/mount.yml
  azure-pipeline-templates/verbose-tests.yml
  blobfuse2-code-coverage.yaml
  blobfuse2-nightly.yaml
  cmd/imports.go
  cmd/mount.go
  cmd/mount_test.go
  common/types.go
  common/util.go
  component/azstorage/azauthmsi.go
  component/azstorage/block_blob.go
  component/block_cache/block.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/block_cache/block_test.go
  component/block_cache/blockpool.go
  component/block_cache/blockpool_test.go
  component/block_cache/threadpool.go
  component/block_cache/threadpool_test.go
  component/file_cache/cache_policy.go
  component/file_cache/cache_policy_test.go
  component/file_cache/file_cache.go
  component/file_cache/lru_policy.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
  component/loopback/loopback_fs.go
  go.mod
  go.sum
  internal/handlemap/handle_map.go
  setup/baseConfig.yaml
  test/benchmark_test/fio.cfg
  test/longhaul/longhaul.sh
  test/scripts/fio.sh
  test/scripts/fio/random_read_20T_100G.fio
  test/scripts/fio/random_read_4T_100G.fio
  test/scripts/fio/random_read_4T_4G.fio
  test/scripts/fio/sequential_read_128T_100G.fio
  test/scripts/fio/sequential_read_1T_4G.fio
  test/scripts/fio/sequential_read_20T_100G.fio
  test/scripts/fio/sequential_read_4T_100G.fio
  test/scripts/fio/sequential_read_4T_4G.fio
  test/scripts/latency_hiding.jl
  test/scripts/parallel_batch_read.py
  test/scripts/profile-latency-hiding.sh
  test/scripts/readwrite.c
  testdata/config/azure_key_bc.yaml
Labels: V2, feature request

#1232 Vibhansa/truncatefile simplify
  CHANGELOG.md
  README.md
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
Labels: V2

#1233 Disk Usage check correction
  CHANGELOG.md
  common/util.go
  common/util_test.go
  component/file_cache/cache_policy.go
  component/file_cache/cache_policy_test.go
Labels: bug, V2
