Repository Azure/azure-storage-fuse, pull requests merged in 2023-11, with the labels that each got.

#1283 Symlink fix for ADLS accounts
  CHANGELOG.md
  azure-pipeline-templates/e2e-tests-spcl.yml
  azure-pipeline-templates/e2e-tests.yml
  azure-pipeline-templates/verbose-tests.yml
  component/azstorage/block_blob.go
  component/azstorage/config.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/libfuse/libfuse_handler.go
  setup/baseConfig.yaml
  test/e2e_tests/dir_test.go
  test/e2e_tests/file_test.go
  testdata/config/azure_key_symlink.yaml
Labels: bug, V2

#1281 Correcting sync to flush behavior
  CHANGELOG.md
  common/types.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
  test/scripts/fsync_sample.c
Labels: bug, V2

#1248 Truncate function changed for streaming
  common/types.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/stream/read_write.go
  component/stream/read_write_test.go
  test/e2e_tests/data_validation_test.go
Labels: bug, V2, streaming

#1286 Rename Directory fix in blob accounts
  CHANGELOG.md
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
Labels: bug, V2

#1267 Randomise refresh token flow
  CHANGELOG.md
  component/azstorage/azauthmsi.go
  component/azstorage/azauthspn.go
  go.mod
  go.sum
Labels: V2, feature request

#1293 Attribute cache invalidation on PathAlreadyExists error
  CHANGELOG.md
  common/types.go
  component/attr_cache/attr_cache.go
  component/azstorage/datalake.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
Labels: bug, V2
