Repository Azure/azure-storage-fuse, pull requests merged in 2023-03, with the labels that each got.

#1082 DFS rename operation not encoding source url
  .github/workflows/codespell.yml
  CHANGELOG.md
  cmd/root.go
  common/types.go
  component/azstorage/datalake.go
  test/e2e_tests/file_test.go
Labels: bug, V2

#1087 Exit with non-zero status code if allow_other is used but not enabled in fuse config
  CHANGELOG.md
  cmd/mount.go
  cmd/mount_test.go
  component/libfuse/libfuse.go
Labels: bug, V2, ready-to-merge

#1088 Fix: async (background) mount may cause problems
  CHANGELOG.md
  README.md
  blobfuse2-nightly.yaml
  cmd/mount.go
  common/util.go
  component/libfuse/libfuse.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
  go.mod
  go.sum
Labels: bug, V2

#1086 sync call can force upload a file to storage if configured
  CHANGELOG.md
  README.md
  component/file_cache/file_cache.go
  setup/baseConfig.yaml
Labels: V2, feature request
