Repository Azure/azure-storage-fuse, pull requests merged in 2023-10, with the labels that each got.

#1253 Refresh token 5 minutes before the expiry
  CHANGELOG.md
  component/azstorage/azauthmsi.go
  component/azstorage/azauthspn.go
  component/block_cache/block_cache.go
  component/file_cache/lru_policy.go
  internal/pipeline_test.go
  test/scripts/readwrite.c
Labels: V2

#1254 Support synfile in stream mode to force upload contents
  CHANGELOG.md
  component/stream/connection.go
  component/stream/read.go
  component/stream/read_test.go
  component/stream/read_write.go
  component/stream/read_write_filename.go
  component/stream/read_write_filename_test.go
  component/stream/read_write_test.go
  component/stream/stream.go
Labels: V2

#1263 Invalid prefetch count shall fail the mount.
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
Labels: V2, block-cache

#1273 Update README.md
  README.md
Labels: documentation, V2

#1276 Respect uid/gid sent over cli param or config file
  CHANGELOG.md
  cmd/mount.go
  common/types.go
  component/libfuse/libfuse.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_defs.h
  component/libfuse/libfuse_handler.go
Labels: bug, V2

#1275 Added decision tree for configuration and fixed config samples
  README.md
  config_decision_tree.png
  sampleFileCacheConfig.yaml
  sampleFileCacheWithSASConfig.yaml
  sampleStreamingConfig.yaml
Labels: V2

#1279 Package refresh
  NOTICE
  go.mod
  go.sum
Labels: V2
