Repository Azure/azure-storage-fuse, pull requests merged in 2023-02, with the labels that each got.

#1045 Updating umask value
  CHANGELOG.md
  cmd/mount.go
Labels: bug, V2

#1044 HNS account needs both dfs and blob endpoint over private-endpoint to work
  TSG.md
Labels: documentation, V2

#1040 Fix Panic generated when user does not have a home directory set
  .gitignore
  CHANGELOG.md
  TSG.md
  cmd/mount.go
  cmd/mount_test.go
  cmd/secure.go
  common/log/logger.go
  common/util.go
  common/util_test.go
  tools/health-monitor/main.go
Labels: bug, V2

#1050 If version check fails to reach public container mount ./all/v1 command is exited
  CHANGELOG.md
  cmd/mount.go
  cmd/mount_all.go
  cmd/mountv1.go
Labels: bug, V2

#1052 Create work dir if it does not exists
  CHANGELOG.md
  cmd/mount.go
Labels: bug, V2

#1069 Getting it ready for 2.0.2 release
  CHANGELOG.md
  go.mod
  go.sum
Labels: V2
