Repository Azure/azure-storage-fuse, pull requests merged in 2024-06, with the labels that each got.

#1428 Create File error code correction for SAS on ADLS
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
Labels: bug, V2

#1431 Removing usage of SPN in pipelines
  .github/workflows/codeql-analysis.yml
  azure-pipeline-templates/blobfuse2-ci-template.yml
  azure-pipeline-templates/build-release.yml
  azure-pipeline-templates/build.yml
  azure-pipeline-templates/distro-tests.yml
  azure-pipeline-templates/e2e-tests-block-cache.yml
  azure-pipeline-templates/e2e-tests-spcl.yml
  azure-pipeline-templates/e2e-tests.yml
  azure-pipeline-templates/setup.yml
  azure-pipeline-templates/verbose-tests.yml
  blobfuse2-ci.yaml
  blobfuse2-code-coverage.yaml
  blobfuse2-nightly.yaml
  component/azstorage/azauth_test.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
  component/file_cache/lfu_policy.go
  component/file_cache/lfu_policy_test.go
  component/file_cache/lru_policy_test.go
  go.mod
  go.sum
  go_installer.sh
  test/e2e_tests/dir_test.go
  testdata/config/azure_key_lfu.yaml
Labels: V2

#1429 Fixing proxy URL parsing
  CHANGELOG.md
  component/azstorage/azauthcli.go
  component/azstorage/azauthkey.go
  component/azstorage/azauthmsi.go
  component/azstorage/azauthsas.go
  component/azstorage/azauthspn.go
  component/azstorage/config.go
  component/azstorage/config_test.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
Labels: bug, V2

#1416 Autoconfig
  .github/CODEOWNERS
  CHANGELOG.md
  README.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  setup/baseConfig.yaml
  setup/devConfig.yaml
Labels: V2, block-cache

#1439 fc autoconfig
  CHANGELOG.md
  README.md
  component/block_cache/block_cache_test.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
  setup/baseConfig.yaml
  setup/devConfig.yaml
Labels: V2
