Repository Azure/azure-storage-fuse, pull requests merged in 2024-04, with the labels that each got.

#1378 libfuse-3.3 does not support 1MB max_write
  CHANGELOG.md
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_wrapper.h
Labels: bug, V2

#1362 CPK support for datalake
  CHANGELOG.md
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
Labels: V2, feature request, Track-2-Migration

#1379 Track2 Migration: Dependency update
  CHANGELOG.md
  common/config/keys_tree_test.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_wrapper.h
  go.mod
  go.sum
Labels: V2, Track-2-Migration

#1373 Add lazy-write feature to make flush and close async in nature.
  CHANGELOG.md
  README.md
  cmd/mount.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
  component/stream/read_write.go
  component/stream/read_write_filename.go
  go_installer.sh
  internal/component_options.go
Labels: V2, feature request

#1380 GO SDK track2 migration
  CHANGELOG.md
  NOTICE
  TSG.md
  common/config/keys_tree_test.go
  common/types.go
  common/version.go
  common/version_test.go
  component/azstorage/azauth.go
  component/azstorage/azauth_test.go
  component/azstorage/azauthkey.go
  component/azstorage/azauthmsi.go
  component/azstorage/azauthsas.go
  component/azstorage/azauthspn.go
  component/azstorage/azstorage.go
  component/azstorage/azstorage_constants.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/config_test.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
  go.mod
  go.sum
  internal/attribute.go
  internal/component_options.go
  setup/baseConfig.yaml
  test/accoutcleanup/accountcleanup_test.go
  test/sdk_test/sdk_test.go
  testdata/config/azure_block_perf.yaml
  testdata/config/azure_key.yaml
  testdata/config/azure_key_bc.yaml
  testdata/config/azure_key_directio.yaml
  testdata/config/azure_key_emptyfile.yaml
  testdata/config/azure_key_hmon.yaml
  testdata/config/azure_key_huge.yaml
  testdata/config/azure_key_lfu.yaml
  testdata/config/azure_key_lru_purge.yaml
  testdata/config/azure_key_perf.yaml
  testdata/config/azure_key_proxy.yaml
  testdata/config/azure_key_symlink.yaml
  testdata/config/azure_msi.yaml
  testdata/config/azure_msi_sysid.yaml
  testdata/config/azure_sas.yaml
  testdata/config/azure_sas_proxy.yaml
  testdata/config/azure_spn.yaml
  testdata/config/azure_spn_proxy.yaml
  testdata/config/azure_stream.yaml
  testdata/config/azure_stream_direct.yaml
  testdata/config/azure_stream_filename.yaml
  testdata/config/azure_stream_filename_direct.yaml
Labels: V2, Track-2-Migration

#1381 Fix fuse minor version check
  CHANGELOG.md
  common/util.go
  common/util_test.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_wrapper.h
Labels: bug, V2

#1382 TLRU large number of threads causing panic
  CHANGELOG.md
  common/types.go
  component/block_cache/block_cache.go
  go.mod
  go.sum
  setup/baseConfig.yaml
Labels: bug, V2

#1384 azcli auth mode
  CHANGELOG.md
  azure-pipeline-templates/blobfuse2-ci-template.yml
  azure-pipeline-templates/build-release.yml
  azure-pipeline-templates/build.yml
  azure-pipeline-templates/verbose-tests.yml
  blobfuse2-code-coverage.yaml
  blobfuse2-nightly.yaml
  component/azstorage/azauth.go
  component/azstorage/azauth_test.go
  component/azstorage/azauthcli.go
  component/azstorage/azauthmsi.go
  component/azstorage/config.go
  setup/baseConfig.yaml
  testdata/config/azure_cli.yaml
Labels: V2, Track-2-Migration
