Repository Azure/azure-storage-fuse, pull requests merged in 2024-09, with the labels that each got.

#1461 Making pipeline consistent with the units
  perf_testing/scripts/highspeed_create.py
  perf_testing/scripts/highspeed_read.py
  perf_testing/scripts/read.py
  perf_testing/scripts/write.py
Labels: bug, V2, ready-to-merge

#1520 Updating codeowners
  .github/CODEOWNERS
Labels: V2

#1518 Fix code coverage tests
  common/util_test.go
Labels: V2, integrity

#1513 README update
  README.md
Labels: V2, block-cache, integrity

#1521 Upgrading go version to 1.23.1
  .github/workflows/trivy.yaml
  go.mod
  go.sum
  go_installer.sh
Labels: V2, ready-to-merge
