Repository Azure/azure-storage-fuse, pull requests merged in 2024-11, with the labels that each got.

#1553 Exposing internal package for custom component feature
  component/block_cache/block_cache.go
  exported/exported.go
  internal/component_options.go
Labels: V2, feature request

#1533 Fix ReadPanic
  CHANGELOG.md
  azure-pipeline-templates/e2e-tests-block-cache-data-integrity.yml
  component/block_cache/block.go
  component/block_cache/block_cache.go
  component/block_cache/block_test.go
  test/e2e_tests/data_validation_test.go
Labels: bug, V2, ready-to-merge, block-cache

#1445 Redirecting stream config to BlockCache
  CHANGELOG.md
  README.md
  azure-pipeline-templates/e2e-tests-block-cache.yml
  blobfuse2-nightly.yaml
  cmd/imports.go
  cmd/mountv1.go
  cmd/mountv1_test.go
  common/util.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/block_cache/stream.go
  component/stream/connection.go
  component/stream/read.go
  component/stream/read_test.go
  component/stream/read_write.go
  component/stream/read_write_filename.go
  component/stream/read_write_filename_test.go
  component/stream/read_write_test.go
  internal/pipeline.go
  internal/pipeline_test.go
  setup/advancedConfig.yaml
  testdata/config/azure_stream.yaml
Labels: V2, ready-to-merge, block-cache, autoconfig

#1558 Adding custom component feature
  CHANGELOG.md
  README.md
  blobfuse2-code-coverage.yaml
  cmd/imports.go
  component/custom/custom.go
  component/custom/custom_test.go
Labels: V2, feature request

#1459 Optimize Rename function logic to reduce the number of REST API calls.
  .gitignore
  CHANGELOG.md
  component/attr_cache/attr_cache.go
  component/azstorage/block_blob.go
Labels: V2, performance, ready-to-merge

#1545 Add Checks for temp path in Block Cache while mouting
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/file_cache/file_cache.go
Labels: bug, V2, ready-to-merge, block-cache

#1557 Support back for object id using azidentity
  CHANGELOG.md
  NOTICE
  component/azstorage/azauthmsi.go
  go.mod
  go.sum
Labels: bug, V2

#1535 Generate default config
  cmd/gen-config.go
  cmd/gen-config_test.go
  cmd/gen-test-config.go
  cmd/mount.go
  common/util.go
  common/util_test.go
  component/attr_cache/attr_cache.go
  component/azstorage/config.go
  component/block_cache/block_cache.go
  component/custom/custom.go
  component/file_cache/file_cache.go
  component/libfuse/libfuse.go
  component/libfuse/libfuse_handler_test.go
  internal/base_component.go
  internal/component.go
  internal/mock_component.go
  internal/pipeline.go
Labels: V2, feature request, ready-to-merge

#1524 Delete empty directories from local cache
  CHANGELOG.md
  component/file_cache/cache_policy.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse2_handler_test_wrapper.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_handler_test_wrapper.go
  internal/base_component.go
  internal/component.go
  internal/mock_component.go
Labels: bug, V2, pr-ready-for-review

#1515 Entry cache component
  CHANGELOG.md
  MIGRATION.md
  blobfuse2-release.yaml
  cmd/imports.go
  cmd/mount.go
  component/attr_cache/attr_cache.go
  component/attr_cache/attr_cache_test.go
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
  component/entry_cache/entry_cache.go
  component/entry_cache/entry_cache_test.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse2_handler_test_wrapper.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_handler_test_wrapper.go
  component/loopback/loopback_fs.go
  internal/attribute.go
  internal/component.template
  internal/component_options.go
  setup/advancedConfig.yaml
Labels: V2, feature request, pr-ready-for-review

#1563 Remove deprecated methods
  cmd/health-monitor_test.go
  cmd/mountv1_test.go
  common/util_test.go
  component/azstorage/block_blob_test.go
  component/azstorage/datalake_test.go
  component/block_cache/block_cache_test.go
  component/entry_cache/entry_cache_test.go
  component/file_cache/file_cache_test.go
  test/e2e_tests/data_validation_test.go
  test/e2e_tests/dir_test.go
  test/e2e_tests/file_test.go
  test/stress_test/stress_test.go
Labels: V2

#1564 E2E tests fix
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
  test/e2e_tests/data_validation_test.go
  test/e2e_tests/dir_test.go
  test/e2e_tests/file_test.go
Labels: V2

#1567 Fix code coverage pipeline
  cmd/mount.go
  cmd/mount_test.go
Labels: V2

#1570 Rocky UT fails due to insufficient memory
  component/block_cache/block_cache_test.go
Labels: bug, V2

#1572 Adding Debian 12
  setup/packages.csv
Labels: V2

#1550 Move version checks from public container to static website
  CHANGELOG.md
  blobfuse2-release.yaml
  cmd/root.go
  cmd/root_test.go
  common/version.go
  releaseVersionUpdate.py
Labels: V2

#1571 Preserve ACL/Permissions while uploading file over datalake
  CHANGELOG.md
  component/azstorage/azstorage.go
  component/azstorage/config.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
  setup/advancedConfig.yaml
Labels: bug, V2
