Repository Azure/azure-storage-fuse, pull requests merged in 2024-05, with the labels that each got.

#1393 Release in Ubuntu 24.04 and Mariner 2.0
  blobfuse2-release.yaml
  setup/packages.csv
Labels: V2

#1387 Get attribute fix for directory with cpk enabled
  CHANGELOG.md
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
Labels: bug, V2

#1403 Update changelog
  CHANGELOG.md
  common/types.go
Labels: V2

#1400 Display mount command
  blobfuse2-release.yaml
  cmd/mount.go
  component/block_cache/block_cache.go
  component/libfuse/libfuse.go
Labels: documentation, V2

#1410 added stream config in devconfig
  setup/devConfig.yaml
Labels: documentation, V2

#1407 Added mount path in the syslog
  cmd/mount.go
  common/log/base_logger.go
  common/log/sys_logger.go
  common/types.go
Labels: documentation, V2

#1406 Update TSG.md
  TSG.md
Labels: documentation, V2

#1398 Add deprecation notice for blobfuse v1
  README.md
Labels: V1

#1408 Vibhansa/rocky
  blobfuse2-nightly.yaml
  blobfuse2-release.yaml
  setup/packages.csv
Labels: V2, feature request

#1414 Updating changelog and dependencies
  CHANGELOG.md
  go.mod
  go.sum
Labels: V2

#1415 Updating changelog for 2.3.1
  CHANGELOG.md
  common/types.go
Labels: V2
