Repository Azure/azure-storage-fuse, pull requests merged in 2024-01, with the labels that each got.

#1311 Mount on non-empty path
  CHANGELOG.md
  azure-pipeline-templates/build.yml
  blobfuse2-nightly.yaml
  cmd/mount.go
  cmd/mount_test.go
  component/libfuse/libfuse_handler.go
  setup/baseConfig.yaml
  test/mount_test/mount_test.go
Labels: bug, V2

#1313 Track2 Migration: Adding auth flows for SPN and MSI
  component/azstorage/t2_azauth.go
  component/azstorage/t2_azauthmsi.go
  component/azstorage/t2_azauthspn.go
  component/azstorage/utils.go
Labels: V2, Track-2-Migration

#1316 Track2 Migration: Adding custom telemetry policy
  common/types.go
  component/azstorage/utils.go
Labels: V2, Track-2-Migration

#1320 Adding config guide
  README.md
  guide/AuthModeHelper.png
  guide/BlockCacheConfig.png
  guide/CacheModeForReadOnlyWorkloads.png
  guide/CacheModeForReadWriteWorkloads.png
  guide/FileCacheConfig.png
Labels: documentation, V2
