Repository Azure/azure-storage-fuse, pull requests merged in 2024-08, with the labels that each got.

#1486 Depdendency upgrade for next release
  common/types.go
  component/block_cache/block_cache.go
  go.mod
  go.sum
  test/longhaul/build_kernel.sh
  test/longhaul/longhaul.sh
Labels: V2, pr-ready-for-review

#1481 Race condition in random write between uploading and writing to a same block
  CHANGELOG.md
  azure-pipeline-templates/e2e-tests-block-cache.yml
  blobfuse2-nightly.yaml
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  test/e2e_tests/data_validation_test.go
  testdata/config/azure_key_bc.yaml
Labels: bug, V2, ready-to-merge, integrity

#1489 Correct SUSE fuse download path
  blobfuse2-nightly.yaml
Labels: V2

#1492 Overwrite when download fails for the given block
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
Labels: V2, ready-to-merge, block-cache, integrity

#1487 Preserve blocks on flush
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
Labels: bug, ready-to-merge, integrity

#1476 Add support for no_proxy
  common/types.go
  component/azstorage/config.go
  component/azstorage/utils.go
Labels: V2, feature request, pr-ready-for-review

#1495 Enabling random write in block cache
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  testdata/config/azure_block_perf.yaml
Labels: V2, block-cache, integrity

#1348 Adding git clone test to block-cache
  azure-pipeline-templates/verbose-tests.yml
Labels: V2, block-cache, integrity

#1496 Cleared all flags and print cooking cooked lists
  component/azstorage/block_blob.go
  component/block_cache/block_cache.go
Labels: V2, block-cache, integrity

#1490 direct-io test in block-cache data validation suite
  azure-pipeline-templates/e2e-tests-block-cache.yml
  azure-pipeline-templates/mount.yml
  blobfuse2-nightly.yaml
Labels: V2, integrity

#1498 Error message for disabling random write in block cache
  common/types.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
Labels: V2, block-cache, integrity

#1462 Block-cache read Pipeline
  azure-pipeline-templates/e2e-tests-block-cache-data-integrity.yml
  blobfuse2-nightly.yaml
  testdata/config/azure_key_bc.yaml
  testdata/scripts/generate-parquet-files.py
Labels: bug, V2, ready-to-merge, block-cache, integrity

#1497 Updating an uncommitted block which has been deleted from buffer cache
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
Labels: V2, block-cache, integrity

#1499 Check download status before overwriting a block
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
Labels: V2, block-cache, integrity

#1506 Added support for mariner preview package release.
  blobfuse2-release.yaml
  cmd/health-monitor.go
  cmd/mount.go
  component/azstorage/azauthmsi.go
  setup/packages.csv
Labels: V2, feature request

#1503 Reading an uncommitted block which has been deleted from buffer cache
  CHANGELOG.md
  azure-pipeline-templates/verbose-tests.yml
  cmd/health-monitor.go
  cmd/mount.go
  component/azstorage/azauthmsi.go
  component/block_cache/block.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/block_cache/block_test.go
Labels: V2, block-cache, integrity

#1491 panic on calling close on close channel
  component/block_cache/block_cache.go
  test/e2e_tests/data_validation_test.go
Labels: V2, block-cache, integrity, pr-ready-for-review

#1508 Data integrity issues in block cache
  CHANGELOG.md
  azure-pipeline-templates/e2e-tests-block-cache-data-integrity.yml
  azure-pipeline-templates/e2e-tests-block-cache.yml
  azure-pipeline-templates/mount.yml
  azure-pipeline-templates/verbose-tests.yml
  blobfuse2-nightly.yaml
  common/types.go
  component/azstorage/config.go
  component/azstorage/utils.go
  component/block_cache/block.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/block_cache/block_test.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
  test/e2e_tests/data_validation_test.go
  testdata/config/azure_block_perf.yaml
  testdata/config/azure_key_bc.yaml
  testdata/scripts/generate-parquet-files.py
Labels: V2, block-cache, integrity

#1502 Correcting file truncation logic in AzStorage component
  CHANGELOG.md
  azure-pipeline-templates/verbose-tests.yml
  common/types.go
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_trucate_test.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/block_cache/block_cache.go
  internal/component_options.go
  test/scripts/flush_test.c
Labels: bug, V2, integrity

#1458 Directory listing caching component
  CHANGELOG.md
  MIGRATION.md
  blobfuse2-release.yaml
  cmd/imports.go
  cmd/mount.go
  component/attr_cache/attr_cache.go
  component/attr_cache/attr_cache_test.go
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
  component/entry_cache/entry_cache.go
  component/entry_cache/entry_cache_test.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse2_handler_test_wrapper.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_handler_test_wrapper.go
  component/loopback/loopback_fs.go
  internal/attribute.go
  internal/component.template
  internal/component_options.go
  setup/advancedConfig.yaml
Labels: V2, feature request

#1511 Update block cache limitations in README
  README.md
  go.mod
  go.sum
Labels: V2, block-cache, integrity
