Repository Azure/azure-storage-fuse, pull requests merged in 2024-07, with the labels that each got.

#1349 Create PerfTest.yml
  .github/template/generate_page/action.yml
  .github/workflows/benchmark.yml
  build.sh
  component/azstorage/block_blob.go
  perf_testing/config/create/1_1000_files_in_10_threads.fio
  perf_testing/config/create/2_1000_files_in_100_threads.fio
  perf_testing/config/create/3_1l_files_in_20_threads.fio
  perf_testing/config/high_threads/1_seq_write_112_threads.fio
  perf_testing/config/high_threads/2_seq_read_128_threads.fio
  perf_testing/config/high_threads/3_rand_read_128_threads.fio
  perf_testing/config/read/1_seq_read.fio
  perf_testing/config/read/2_rand_read.fio
  perf_testing/config/read/3_seq_read_small.fio
  perf_testing/config/read/4_rand_read_small.fio
  perf_testing/config/read/5_seq_read_directio.fio
  perf_testing/config/read/6_rand_read_directio.fio
  perf_testing/config/read/7_seq_read_4thread.fio
  perf_testing/config/read/8_seq_read_16thread.fio
  perf_testing/config/read/9_rand_read_4thread.fio
  perf_testing/config/write/1_seq_write.fio
  perf_testing/config/write/2_seq_write_directio.fio
  perf_testing/config/write/3_seq_write_4thread.fio
  perf_testing/config/write/4_seq_write_16thread.fio
  perf_testing/scripts/fio_bench.sh
  perf_testing/scripts/highspeed_create.py
  perf_testing/scripts/highspeed_read.py
  perf_testing/scripts/read.py
  perf_testing/scripts/rename.py
  perf_testing/scripts/write.py
  sampleDataSetFuseConfig.json
  testdata/config/azure_block_bench.yaml
Labels: V2, performance

#1448 Remove RHEL 7.5 from nightly and artifacts.
  blobfuse2-nightly.yaml
  blobfuse2-release.yaml
Labels: V2

#1454 Fixed block-cache test
  component/block_cache/block_cache_test.go
Labels: V2

#1452 ObjectID info updated and simplified base config
  README.md
  cmd/mount.go
  setup/advancedConfig.yaml
  setup/baseConfig.yaml
Labels: V2

#1453 Cleanup stale mount in remount case
  CHANGELOG.md
  cmd/mount.go
  common/util.go
  common/util_test.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/file_cache/file_cache.go
Labels: bug, V2

#1464 Updating TSG for proxy environment
  TSG.md
Labels: documentation, V2

#1467 Reset block when released
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/blockpool.go
  component/block_cache/blockpool_test.go
Labels: bug, V2, block-cache

#1477 Update README.md
  README.md
Labels: documentation, V2

#1480 Update README.md
  README.md
Labels: documentation, V2, integrity

#1473 Blocker and Vulnerability update
  cmd/root.go
  cmd/root_test.go
  common/version.go
Labels: V2, feature request, integrity

#1472 Block cache openFile if condition bug
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
Labels: bug, V2, integrity

#1475 Block cache random write in sparse files
  CHANGELOG.md
  azure-pipeline-templates/verbose-tests.yml
  component/block_cache/block.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/libfuse/libfuse_handler.go
  component/loopback/loopback_fs.go
  component/loopback/loopback_fs_test.go
  internal/component_options.go
  test/e2e_tests/data_validation_test.go
Labels: bug, V2, integrity

#1483 Block Cache Read correction
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  test/e2e_tests/data_validation_test.go
Labels: bug, V2, block-cache, integrity

#1484 Block cache disable random write
  CHANGELOG.md
  azure-pipeline-templates/cleanup.yml
  azure-pipeline-templates/e2e-tests-block-cache.yml
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/block_cache/blockpool_test.go
  testdata/config/azure_block_perf.yaml
  testdata/config/azure_key_bc.yaml
Labels: bug, V2, block-cache, integrity
