Repository Azure/azure-storage-fuse, pull requests merged in 2024-03, with the labels that each got.

#1352 remove redundant error check
  component/azstorage/datalake.go
Labels: Track-2-Migration

#1353 Track2 Migration: Update SDK dependencies
  blobfuse2-nightly.yaml
  component/azstorage/azauth_test.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
  go.mod
  go.sum
Labels: V2, Track-2-Migration

#1355 Track2 Migration: Adding headers and query params to be logged
  component/azstorage/azstorage_constants.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/utils.go
Labels: Track-2-Migration

#1364 Add mount all limitation
  README.md
Labels: documentation, V2

#1365 Track2 Migration: Enable SDK logging on debug mode
  TSG.md
  component/azstorage/azauth.go
  component/azstorage/azauthspn.go
  component/azstorage/azstorage.go
  component/azstorage/azstorage_constants.go
  component/azstorage/config.go
  component/azstorage/connection.go
  component/azstorage/utils.go
  setup/baseConfig.yaml
  testdata/config/azure_block_perf.yaml
  testdata/config/azure_key.yaml
  testdata/config/azure_key_bc.yaml
  testdata/config/azure_key_directio.yaml
  testdata/config/azure_key_emptyfile.yaml
  testdata/config/azure_key_hmon.yaml
  testdata/config/azure_key_huge.yaml
  testdata/config/azure_key_lfu.yaml
  testdata/config/azure_key_lru_purge.yaml
  testdata/config/azure_key_perf.yaml
  testdata/config/azure_key_proxy.yaml
  testdata/config/azure_key_symlink.yaml
  testdata/config/azure_msi.yaml
  testdata/config/azure_msi_sysid.yaml
  testdata/config/azure_sas.yaml
  testdata/config/azure_sas_proxy.yaml
  testdata/config/azure_spn.yaml
  testdata/config/azure_spn_proxy.yaml
  testdata/config/azure_stream.yaml
  testdata/config/azure_stream_direct.yaml
  testdata/config/azure_stream_filename.yaml
  testdata/config/azure_stream_filename_direct.yaml
Labels: Track-2-Migration

#1366 Track2 Migration: Updating version check logic for preview releases
  CHANGELOG.md
  common/types.go
  common/version.go
  common/version_test.go
  component/azstorage/azstorage.go
  component/azstorage/utils.go
Labels: V2, Track-2-Migration
