Repository Azure/azure-storage-fuse, pull requests merged in 2025-02, with the labels that each got.

#1618 BUG#31069208: Fixed Prefix filtering from File Path
  CHANGELOG.md
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
Labels: bug, V2, pr-ready-for-review

#1616 Documentation on required private endpoints to access hns enabled storage
  CHANGELOG.md
  README.md
Labels: documentation, V2, pr-ready-for-review

#1628 Create highspeed_write_nonzero.py
  perf_testing/scripts/highspeed_write_nonzero.py
Labels: V2

#1622 Bug Fixes for Release 2.4.1
  CHANGELOG.md
  azure-pipeline-templates/scripts/ubn-setup.sh
  blobfuse2-nightly.yaml
  component/attr_cache/attr_cache.go
  component/attr_cache/attr_cache_test.go
  component/azstorage/block_blob.go
  component/azstorage/datalake.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
  component/block_cache/block_cache.go
  component/block_cache/threadpool.go
  component/file_cache/file_cache.go
  component/libfuse/libfuse2_handler.go
  go.mod
  go.sum
  test/e2e_tests/file_test.go
Labels: V2

#1627 File open call in preload
  component/azstorage/azstorage.go
  component/xload/blockpool.go
  component/xload/splitter.go
  component/xload/threadpool.go
  component/xload/utils.go
  component/xload/xload.go
Labels: V2, xload

#1636 Cancel download of a blob if one block fails + Unit tests
  component/loopback/loopback_fs.go
  component/xload/block_test.go
  component/xload/blockpool.go
  component/xload/blockpool_test.go
  component/xload/data_manager.go
  component/xload/data_manager_test.go
  component/xload/lister.go
  component/xload/lister_test.go
  component/xload/splitter.go
  component/xload/splitter_test.go
  component/xload/stats_manager.go
  component/xload/threadpool_test.go
  component/xload/utils.go
  component/xload/utils_test.go
  component/xload/xload.go
  component/xload/xload_test.go
Labels: V2, xload

#1637 In case of mount and mount all, if the container name has '$' do not treat it as env variable
  common/types.go
  common/util.go
  common/util_test.go
Labels: bug, V2

#1620 Add support for client assertion based authentication
  CHANGELOG.md
  blobfuse2-code-coverage.yaml
  common/types.go
  component/azstorage/azauth.go
  component/azstorage/azauthclientassertion.go
  component/azstorage/config.go
Labels: V2, feature request

#1642 Xload: Unit tests
  common/types.go
  component/xload/data_manager.go
  component/xload/data_manager_test.go
  component/xload/lister.go
  component/xload/splitter.go
  component/xload/splitter_test.go
  component/xload/stats_manager.go
  component/xload/stats_manager_test.go
  component/xload/utils.go
  component/xload/utils_test.go
  component/xload/xcomponent.go
  component/xload/xload.go
  component/xload/xload_test.go
Labels: V2, xload
