Repository Azure/azure-storage-fuse, pull requests merged in 2025-01, with the labels that each got.

#1602 Fix Dependabot alerts
  go.mod
  go.sum
Labels: V2

#1555 Use ListBlob for hns accounts
  MIGRATION.md
  README.md
  azure-pipeline-templates/huge-list-test.yml
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
  go.mod
  go.sum
Labels: pr-ready-for-review

#1470 Added statfs for block-cache
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
Labels: bug, V2, block-cache, pr-ready-for-review

#1604 Add strong consistency check for data on disk
  CHANGELOG.md
  README.md
  common/util.go
  common/util_test.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
Labels: V2, integrity, pr-ready-for-review

#1580 bug in block cache open call
  CHANGELOG.md
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/loopback/loopback_fs.go
  component/loopback/loopback_fs_test.go
Labels: bug, ready-to-merge

#1595 Feature: Blob filter
  CHANGELOG.md
  NOTICE
  README.md
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/config.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
  component/azstorage/utils.go
  go.mod
  go.sum
  internal/attribute.go
Labels: V2, feature request, pr-ready-for-review

#1613 After an ungraceful unmount, mount shall cleanup temp-cache only if flag is set
  CHANGELOG.md
  cmd/mount.go
Labels: bug, V2, pr-ready-for-review

#1575 Automate blobfuse2 setup for new VM
  setup/setupUBN.sh
  setup/vmSetupAzSecPack.sh
Labels: V2, pr-ready-for-review

#1619 Downgrade go version to protect against memory issues found by Azcopy in 1.23.1
  go.mod
  go.sum
  go_installer.sh
Labels: bug, V2, ready-to-merge

#1608 Enable ETAG based validation on every block download to provide higher consistency
  CHANGELOG.md
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
  component/block_cache/block_cache.go
  internal/attribute.go
  internal/component_options.go
Labels: V2, feature request, ready-to-merge

#1614 Reduce the number of rest calls while doing Rename Operation
  CHANGELOG.md
  component/attr_cache/attr_cache.go
  component/attr_cache/attr_cache_test.go
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/connection.go
  component/azstorage/datalake.go
  component/azstorage/utils.go
  component/libfuse/libfuse_handler.go
  internal/component_options.go
  internal/mock_component.go
Labels: V2, performance, pr-ready-for-review
