Repository Azure/azure-storage-fuse, pull requests merged in 2025-08, with the labels that each got.

#1819 Modernize go code using modernize tool
  cmd/health-monitor_stop.go
  cmd/mount.go
  cmd/mountgen1.go
  cmd/root.go
  common/config/config_parser.go
  common/config/keys_tree.go
  common/config/keys_tree_test.go
  common/log/base_logger.go
  common/log/logger.go
  common/log/logger_test.go
  common/log/silent_logger.go
  common/log/sys_logger.go
  common/util.go
  common/version.go
  component/azstorage/azauth.go
  component/azstorage/azauthWorkloadIdentity.go
  component/azstorage/azauthcli.go
  component/azstorage/azauthkey.go
  component/azstorage/azauthmsi.go
  component/azstorage/azauthsas.go
  component/azstorage/azauthspn.go
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/datalake_test.go
  component/azstorage/utils.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/block_cache/blockpool.go
  component/block_cache/blockpool_test.go
  component/block_cache/threadpool_test.go
  component/custom/custom.go
  component/file_cache/file_cache_test.go
  component/loopback/loopback_fs.go
  component/xload/blockpool.go
  component/xload/blockpool_test.go
  component/xload/lister_test.go
  component/xload/splitter_test.go
  component/xload/stats_manager_test.go
  component/xload/threadpool_test.go
  internal/handlemap/handle_map.go
  internal/stats_manager/stats_manager.go
  test/e2e_tests/data_validation_test.go
  test/e2e_tests/dir_test.go
  test/e2e_tests/file_test.go
  tools/health-monitor/common/util.go
  tools/health-monitor/internal/monitor.go
  tools/health-monitor/internal/stats_export.go
  tools/health-monitor/monitor/blobfuse_stats/stats_reader.go
  tools/health-monitor/monitor/cpu_mem_profiler/cpu_mem_monitor.go
  tools/health-monitor/monitor/file_cache/cache_monitor.go
  tools/health-monitor/monitor/network_profiler/network_monitor.go
Labels: enhancement

#1907 Fixed some stats to be more meaningful
  internal/dcache/cluster_manager/cluster_manager.go
  internal/dcache/debug/stats/stats.go
  internal/dcache/metadata_manager/metadata_manager_impl.go
Labels: dcache

#1901 Convert read options struct to pointer in the pipeline
  component/azstorage/azstorage.go
  component/azstorage/block_blob_test.go
  component/azstorage/datalake_test.go
  component/block_cache/block_cache.go
  component/block_cache/block_cache_test.go
  component/file_cache/file_cache.go
  component/file_cache/file_cache_test.go
  component/libfuse/libfuse2_handler.go
  component/libfuse/libfuse_handler.go
  component/loopback/loopback_fs.go
  component/loopback/loopback_fs_test.go
  component/xload/data_manager.go
  internal/base_component.go
  internal/component.go
  internal/mock_component.go
Labels: pr-ready-for-review

#1909 Add heartbeat and other stats.
  internal/dcache/cluster_manager/cluster_manager.go
  internal/dcache/debug/stats/stats.go
Labels: pr-ready-for-review, dcache

#1905 Don't auto-detect account if --use-adls flag is given
  component/azstorage/azstorage.go
Labels: pr-ready-for-review

#1913 fix e2e tests failure
  test/e2e_tests/dir_test.go
  test/e2e_tests/file_test.go
Labels: pr-ready-for-review

#1916 Update MV placer to honor fault domains when choosing component RVs, and many other scale and correctness fixes
  common/assert.go
  common/util.go
  component/distributed_cache/distributed_cache.go
  component/distributed_cache/utils.go
  internal/dcache/cluster_manager/cluster_manager.go
  internal/dcache/clustermap/clustermap.go
  internal/dcache/clustermap/clustermap_dummy_success.json
  internal/dcache/clustermap/utils.go
  internal/dcache/metadata_manager/metadata_manager_impl.go
  internal/dcache/models.go
  internal/dcache/rpc/server/handler.go
Labels: dcache

#1923 Personal/linuxsmiths/my experiments with fuse
  component/libfuse/libfuse.go
  component/libfuse/libfuse_handler.go
  component/libfuse/libfuse_handler_test_wrapper.go
Labels: pr-ready-for-review, dcache

#1920 Removed Dependency of RVId generation over filesysem and also handled cache directory creation if doesn't exist
  component/distributed_cache/distributed_cache.go
  component/distributed_cache/utils.go
  internal/dcache/cluster_manager/cluster_manager.go
  internal/dcache/clustermap/utils.go
Labels: pr-ready-for-review, dcache
