Repository Azure/azure-storage-fuse, pull requests merged in 2025-03, with the labels that each got.

#1646 Rename ClientAssertion to WorkloadIdentity
  CHANGELOG.md
  README.md
  blobfuse2-code-coverage.yaml
  component/azstorage/azauth.go
  component/azstorage/azauthWorkloadIdentity.go
  component/azstorage/config.go
Labels: V2, feature request

#1648 return the detailed error when the connection fails
  component/azstorage/azstorage.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/datalake.go
  component/azstorage/datalake_test.go
Labels: ready-to-merge

#1641 Go upgrade to latest version
  cmd/mount.go
  component/azstorage/utils.go
  go.mod
  go.sum
  go_installer.sh
Labels: V2

#1644 Xload: Add consistency check
  common/util.go
  common/util_test.go
  component/azstorage/block_blob.go
  component/azstorage/block_blob_test.go
  component/azstorage/utils.go
  component/azstorage/utils_test.go
  component/loopback/loopback_fs.go
  component/xload/data_manager.go
  component/xload/data_manager_test.go
  component/xload/lister.go
  component/xload/lister_test.go
  component/xload/splitter.go
  component/xload/splitter_test.go
  component/xload/utils.go
  component/xload/xload.go
  component/xload/xload_test.go
Labels: V2, ready-to-merge, xload

#1650 Xload: E2E tests
  azure-pipeline-templates/e2e-tests-xload.yml
  blobfuse2-nightly.yaml
  component/xload/splitter.go
  testdata/config/azure_key_xload.yaml
Labels: V2, ready-to-merge, xload
